name: 'schedule-job-action'
description: 'Schedule a delayed job in GitHub Actions'
author: 'cardinalby'
inputs:
  ghToken:
    description: 'Special GitHub access token with `workflows` permission'
    required: true
  templateYmlFile:
    description: 'Path (relative to repo) to template yml file'
    required: true
  overrideTargetFile:
    description: 'Override target file if exists. "true" or "false"'
    default: 'true'
    required: false
  targetYmlFileName:
    description: 'Name of target yml file to create in .github/workflows dir'
    required: false
  targetRepo:
    description: 'Repository to add the delayed workflow to. Format: owner-name/repo-name'
    required: false
  targetBranch:
    description: 'Branch to push changes. If not specified, repository default branch is used'
    required: false
  pushForce:
    description: 'Perform push with force flag'
    required: false
    default: 'true'
  addTag:
    description: 'Name of tag to create (if you want to schedule a job to checkout a tag)'
    required: false
  jobPayload:
    description: 'Pass a string to DELAYED_JOB_PAYLOAD env variable in delayed workflow file'
    required: false
  copyEnvVariables:
    description: 'names of env variables which values should be copied to the jobs in the scheduled workflow'
    required: false
outputs:
  targetYmlFileName:
    description: 'File name of new yml file'
  targetYmlFilePath:
    description: 'Absolute path to new yml file'
runs:
  using: 'node16'
  main: 'dist/index.js'
branding:
  icon: 'tag'
